version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5511:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: verkeersborden
      POSTGRES_USER: verkeersborden
  current_traffic_signs:
    build: .
    links:
      - database
    environment:
      OBJECTSTORE_PASSWORD:
    command: >
        bash -c "/app/download_files.sh && /app/import_files_to_postgres.sh && /app/import_panos_to_postgres.sh"